inherit_from: .rubocop_todo.yml

# RuboCop設定ファイル
# 学習目的で最小限の設定

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'Dockerfile*'
    - 'docker-compose*.yml'

# 学習段階では緩い設定
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 21

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'

Metrics/ClassLength:
  Max: 150
  Exclude:
    - 'app/controllers/users_controller.rb'  # Phase 3で対応予定