version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
      - bundle_cache:/bundle
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql2://root:password@db:3306/attendance_app_development
      - RAILS_ENV=development
    stdin_open: true
    tty: true

  db:
    image: mysql:8.0.35
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: attendance_app_development
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
  bundle_cache: